# Generated by Django 5.2.9 on 2025-12-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('plan_num', models.IntegerField(help_text='Número de facturas permitidas al año')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigencia', models.IntegerField(help_text='Vigencia en meses o días según lógica de negocio')),
            ],
        ),
        migrations.CreateModel(
            name='DatosProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('representante', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServidorBaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_identificador', models.CharField(help_text='Ej: Servidor Principal, Servidor Secundario', max_length=50)),
                ('ip_host', models.CharField(help_text='Dirección IP o DNS del servidor SQL', max_length=50)),
                ('puerto', models.IntegerField(default=1433)),
                ('usuario_sql', models.CharField(help_text='Usuario con permisos de lectura', max_length=100)),
                ('clave_sql', models.CharField(help_text='Contraseña de conexión a la BD externa', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatosServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_renovacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('facturas_consumidas', models.IntegerField(default=0, help_text='Actualizado automáticamente desde BD externa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.datosproducto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.datosproveedor')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empresaexterna')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.estadocliente')),
            ],
        ),
        migrations.CreateModel(
            name='DatosGeneralesCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_cliente', models.CharField(max_length=200)),
                ('ruc_cliente', models.CharField(max_length=13, unique=True)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('correo_cliente', models.EmailField(max_length=50)),
                ('contacto_alt', models.BooleanField(default=False)),
                ('telefono_alt', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_alt', models.EmailField(blank=True, max_length=100, null=True)),
                ('observacion_alt', models.TextField(blank=True, null=True)),
                ('regimen', models.CharField(max_length=50)),
                ('precio_pactado', models.DecimalField(decimal_places=2, help_text='Precio real vendido al cliente', max_digits=10)),
                ('motivo_precio', models.TextField(blank=True, null=True)),
                ('envio_email', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.datosservicio')),
            ],
        ),
        migrations.CreateModel(
            name='DatosTecnicosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_basedatos', models.CharField(help_text='Nombre de la BD en SQL Server', max_length=100)),
                ('url_portal', models.URLField(blank=True, null=True)),
                ('clave_portal', models.CharField(blank=True, max_length=100, null=True)),
                ('num_portal', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('firma', models.CharField(blank=True, max_length=100, null=True)),
                ('num_servicios', models.IntegerField(blank=True, null=True)),
                ('email_tecnico', models.EmailField(blank=True, max_length=100, null=True)),
                ('clave_email', models.CharField(blank=True, max_length=100, null=True)),
                ('code_email', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_tecnicos', to='gestion.datosgeneralescliente')),
                ('servidor_alojamiento', models.ForeignKey(help_text='Servidor físico donde está la BD', on_delete=django.db.models.deletion.PROTECT, to='gestion.servidorbasedatos')),
            ],
        ),
    ]
