# Generated by Django 5.2.9 on 2025-12-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosservicio',
            name='empresa',
        ),
        migrations.AddField(
            model_name='datosgeneralescliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cliente Activo'),
        ),
        migrations.AddField(
            model_name='datosservicio',
            name='mod_compras',
            field=models.BooleanField(default=False, verbose_name='Compras (Liq/Ret)'),
        ),
        migrations.AddField(
            model_name='datosservicio',
            name='mod_inventario',
            field=models.BooleanField(default=False, verbose_name='Inventario (Kardex)'),
        ),
        migrations.AddField(
            model_name='datosservicio',
            name='mod_tesoreria',
            field=models.BooleanField(default=False, verbose_name='Tesoreria (C x P/C)'),
        ),
        migrations.AddField(
            model_name='datosservicio',
            name='mod_ventas',
            field=models.BooleanField(default=False, verbose_name='Ventas (Facturación)'),
        ),
    ]
