# Generated by Django 5.2.9 on 2025-12-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_datosservicio_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosservicio',
            name='fecha_caducidad_firma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Caducidad Firma'),
        ),
    ]
