# Generated by Django 5.2.9 on 2025-12-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_datosservicio_fecha_caducidad_firma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpresaExterna',
        ),
        migrations.AlterField(
            model_name='datosgeneralescliente',
            name='correo_cliente',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datosgeneralescliente',
            name='ruc_cliente',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC Cliente'),
        ),
        migrations.AlterField(
            model_name='datosgeneralescliente',
            name='telefono_alt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datosgeneralescliente',
            name='telefono_cliente',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datosproveedor',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC Proveedor'),
        ),
        migrations.AlterField(
            model_name='datosproveedor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
