# Generated by Django 5.2.9 on 2025-12-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_delete_empresaexterna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosservicio',
            name='fecha_caducidad_firma',
            field=models.DateField(blank=True, null=True, verbose_name='Caducidad Firma'),
        ),
    ]
