# Generated by Django 5.2.9 on 2025-12-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_datosservicio_fecha_caducidad_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='datosgeneralescliente',
            name='regimen',
        ),
    ]
