# Generated by Django 5.2.9 on 2025-12-29 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_datosregimen_remove_datosgeneralescliente_regimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgeneralescliente',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.datosregimen', verbose_name='Régimen Tributario'),
        ),
    ]
