# Generated by Django 5.2.9 on 2026-01-04 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_datosgeneralescliente_regimen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosgeneralescliente',
            name='precio_pactado',
        ),
        migrations.RemoveField(
            model_name='datosservicio',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='datosservicio',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Servicio'),
        ),
        migrations.AddField(
            model_name='datosservicio',
            name='precio_pactado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio real vendido al cliente', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosgeneralescliente',
            name='regimen',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.datosregimen', verbose_name='Régimen Tributario'),
        ),
        migrations.AlterField(
            model_name='datosservicio',
            name='estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='gestion.estadocliente'),
        ),
        migrations.AlterField(
            model_name='datosservicio',
            name='proveedor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='gestion.datosproveedor'),
        ),
    ]
