# Generated by Django 5.2.9 on 2026-01-04 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_datosgeneralescliente_precio_pactado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosservicio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='datosservicio',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='datosgeneralescliente',
            name='estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='gestion.estadocliente'),
        ),
        migrations.AddField(
            model_name='datosgeneralescliente',
            name='proveedor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='gestion.datosproveedor'),
        ),
    ]
