# Generated by Django 5.2.9 on 2026-01-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_datosservicio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosservicio',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='datosgeneralescliente',
            name='estado',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='gestion.estadocliente'),
        ),
    ]
