# Generated by Django 5.2.9 on 2026-01-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_datosservicio_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosgeneralescliente',
            name='motivo_precio',
        ),
    ]
